text = input("Enter a string: ")
# Demonstrating string functions
print("\n--- String Function Demonstration ---")
print("Original String :", text)
print("Length :", len(text))
print("Uppercase :", text.upper())
print("Lowercase :", text.lower())
print("Title Case :", text.title())
print("Capitalize :", text.capitalize())
print("Reversed String :", text[::-1])
print("Is Alphabetic :", text.isalpha())
print("Is Digit :", text.isdigit())
print("Count of 'a' :", text.count('a'))
print("Find 'is' :", text.find('is'))
print("Replace 'a' with '@':", text.replace('a', '@'))
print("Split by space :", text.split())
print("Strip spaces :", text.strip())